server:
  port: 8081

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #gateway开启服务注册和发现
          lower-case-service-id: true #将请求路径上的服务名配置为小写
      routes:
        - id: get_route
          uri: http://httpbin.org/
          predicates:
            - Path=/get
        - id: cookie_route
          uri: http://localhost:8762/
          predicates:
            - Cookie=username,zlf #只有带cookie的才能匹配到这个路由
          filters:
            - name: Hystrix #断路器 服务降级
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter #限流
              args:
                redis-rate-limiter.replenishRate: 1 #每秒允许处理的请求数量
                redis-rate-limiter.burstCapacity: 2 #每秒最大处理的请求数量
                key-resolver: "#{@ipKeyResolver}"
  redis:
    host: 106.12.91.187
    password: zlf1997!


eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:8760/eureka/