server:
  port: 8760

spring:
  application:
    name: peer1

eureka:
  instance:
    hostname: peer1
  client:
    #    #表示自身是eureka-server
    #    register-with-eureka: false
    #    fetch-registry: false
    #eureka的服务注册地址
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true #注册中心相互注册
    fetch-registry: true
#      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
