spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true

---
spring:
  profiles: peer1

server:
  port: 8760

eureka:
  instance:
    hostname: peer1

  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/


---
spring:
  profiles: peer2

server:
  port: 8761

eureka:
  instance:
    hostname: peer2

  client:
    service-url:
      defaultZone: http://peer1:8760/eureka