server:
  port: 8764

spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://106.12.91.187:9411/

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/